id: A7701AF96
title: 'The Tamboura of Devotion: A Prayer to Götsang Gönpo Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:26:00.607678
  last_modified_at: 2022-02-28 23:26:00.607683
